server:
  port: 9002
spring:
  profiles: dev #开发环境
  application:
    name: HRM-COURSE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_course
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/liqiang/hrm/mapper/*Mapper.xml
  type-aliases-package: com.liqiang.hrm.domain,com.liqiang.hrm.query