spring:
  profiles:
    active:
    - dev
---
server:
  port: 9001
spring:
  profiles: dev #开发环境
  application:
    name: HRM-SYSTEM
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_system
    username: root
    password: 123456
---
server:
  port: 9001
spring:
  profiles: test #测试环境 
  application:
    name: HRM-SYSTEM # 这里取名就是注册到Eureka的名字，如果开发HRM-SYSTEM-DEV和测试名字HRM-SYSTEM-TEST不一样，那么zuul里面映射不好配置的
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_system
    username: root
    password: 123456
---
mybatis-plus:
  mapper-locations: classpath:com/liqiang/hrm/mapper/*Mapper.xml
  type-aliases-package: com.liqiang.hrm.domain,com.liqiang.hrm.query