server:
  port: 4399
spring:
  application:
    name: hrm-zuul-gateway
zuul:
  routes:
    system.serviceId: hrm-system #  需要被通过网关（再通过Eureka）访问的服务的服务名  必须和注册到Eureka的name一致才能找到，因为配置到github的name取了dev（挖坑），这里也必须dev
    system.path: /system/** # 把/system打头的所有请求都转发给hrm-system
    course.serviceId: hrm-course #  需要被通过网关访问的服务的服务名    注释放开后，空格变少，，就会不生效，，，切记！！
    course.path: /course/** # 把/course打头的所有请求都转发给hrm-course
    fastdfs.serviceId: hrm-fastdfs #  需要被通过网关访问的服务的服务名    注释放开后，空格变少，，就会不生效，，，切记！！
    fastdfs.path: /fastdfs/** # 把/fastdfs打头的所有请求都转发给hrm-fastdfs
  ignored-services: "*"
  prefix: /services
  retryable: true #是否重试
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：3000ms